#ifndef SIMCRAFT_HAIRSIM_INCLUDE_HAIRSIM_CONSTRAINTS_H_
#define SIMCRAFT_HAIRSIM_INCLUDE_HAIRSIM_CONSTRAINTS_H_

namespace hairsim {

struct Constraint {

};

}

#endif // SIMCRAFT_HAIRSIM_INCLUDE_HAIRSIM_CONSTRAINTS_H_