//
// Created by creeper on 4/26/24.
//

#ifndef SIMCRAFT_FLUIDSIM_INCLUDE_FLUIDSIM_CUDA_CUDA_LINALG_CUH_
#define SIMCRAFT_FLUIDSIM_INCLUDE_FLUIDSIM_CUDA_CUDA_LINALG_CUH_
namespace fluid::cuda {

}
#endif //SIMCRAFT_FLUIDSIM_INCLUDE_FLUIDSIM_CUDA_CUDA_LINALG_CUH_
