//
// Created by creeper on 10/22/24.
//

#ifndef SIMCRAFT_FEM_INCLUDE_FEM_PRIMITIVES_ELASTIC_STRING_H_
#define SIMCRAFT_FEM_INCLUDE_FEM_PRIMITIVES_ELASTIC_STRING_H_
namespace fem {
struct ElasticString {

};
}
#endif //SIMCRAFT_FEM_INCLUDE_FEM_PRIMITIVES_ELASTIC_STRING_H_
