//
// Created by creeper on 6/18/24.
//

#ifndef SIMCRAFT_OGLRENDER_INCLUDE_OGL_RENDER_PLATFORM_H_
#define SIMCRAFT_OGLRENDER_INCLUDE_OGL_RENDER_PLATFORM_H_

#define BUILTIN_SHADER_DIR OGL_RENDER_SOURCE_DIR"/shaders"

#endif //SIMCRAFT_OGLRENDER_INCLUDE_OGL_RENDER_PLATFORM_H_
